#Makefile for NetDev_Chain Notifier Call Chain

obj-m += netdevchain.o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

